import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { GoogleGenAI } from '@google/genai';
import dotenv from 'dotenv';
import crypto from 'crypto';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
dotenv.config({ path: path.resolve(__dirname, '.env') });

const IMAGES_DIR = path.resolve(__dirname, 'תמונות מקור');
const DATA_FILE = path.resolve(__dirname, '../data.json');

// Initialize Gemini Client
const apiKey = process.env.GEMINI_API_KEY;
if (!apiKey) {
    console.error('❌ שגיאה: נא להגדיר GEMINI_API_KEY בקובץ .env באותיות רישיות');
    process.exit(1);
}
const ai = new GoogleGenAI({ apiKey });

// Load existing data
const data = JSON.parse(fs.readFileSync(DATA_FILE, 'utf-8'));

const SYSTEM_PROMPT = `
אתה מומחה לשפה העברית ולמשחקי מילים כפל-לשון.
מוצגת בפניך תמונה שנוצרה ב-AI כדי להמחיש משחק מילים.
שים לב: שם הקובץ עשוי לתת לך רמז על משחק המילים, אבל הוא עשוי גם להיות שגוי או גנרי (למשל 'חמץ גמור' לרוב התמונות).
חובה למצוא את משחק המילים כתוב טקסטואלית על התמונה עצמה (לרוב בעברית, לעיתים נדירות גם באנגלית).

המטרה שלך:
1. לקרוא את הטקסט (הביטוי) מתוך התמונה ולהשתמש בו ככותרת האמיתית. אם הטקסט באנגלית, תרגם אותו לעברית.
2. לסווג את התמונה לקטגוריה/נושא (topic) קצרה, למשל 'אוכל', 'צבא', 'חיות'.
3. לכתוב פסקת הסבר קצרה (2-3 משפטים) שמסבירה את כפל הלשון.

הסבר תמיד באותו מבנה:
1. מהו הביטוי המקורי / הנכון?
2. איך המילים המרכיבות אותו נשמעות או מתפרשות אחרת?
3. תאר מה רואים בתמונה שמתחבר לפירוש השני המצחיק.

עליך להחזיר **אובייקט JSON חוקי בלבד** (ללא Markdown markdown עטוף) במבנה הבא:
{
  "title": "הביטוי_מהתמונה",
  "topic": "קטגוריה",
  "explanation": "פסקת_הסבר"
}
`;

function extractTitle(filename) {
    const noExt = filename.replace(/\.(png|jpe?g)$/i, '');
    return noExt.replace(/_\d{8}_\d{6}(_\d{4})?$/, '').trim();
}

// Convert local file to the format Gemini expects for inlineData
function fileToGenerativePart(filePath, mimeType) {
    return {
        inlineData: {
            data: Buffer.from(fs.readFileSync(filePath)).toString("base64"),
            mimeType
        },
    };
}

async function analyzeImage(filename, retries = 3) {
    try {
        const title = extractTitle(filename);
        console.log(`\n⏳ מנתח: "${title}" (${filename})`);

        const filePath = path.join(IMAGES_DIR, filename);
        const mimeType = filename.toLowerCase().endsWith('.png') ? 'image/png' : 'image/jpeg';
        const imagePart = fileToGenerativePart(filePath, mimeType);

        // אם השם הוא גנרי מדי, לא נספק אותו כרמז כדי לא לבלבל את ה-AI
        const isGeneric = title.includes('חמץ גמור') || title.includes('עיצוב ללא שם') || title.includes('טקסט הפסקה שלך');
        const hintText = isGeneric ? "שם הקובץ הוא גנרי (התעלם ממנו)." : `שם הקובץ (כרמז אפשרי, לא מחייב): "${title}"`;

        const prompt = `${hintText}\nחובה למצוא את הטקסט הכתוב פיזית בתוך התמונה ולהתבסס רק עליו כשם משחק המילים (הכותרת). בנוסף, מצא נושא (topic) קצר שמתאים לתמונה והסבר קצר על הביטוי.`;

        const response = await ai.models.generateContent({
            model: 'gemini-2.5-flash',
            contents: [
                {
                    role: 'user',
                    parts: [
                        { text: prompt },
                        imagePart
                    ]
                }
            ],
            config: {
                systemInstruction: SYSTEM_PROMPT,
                temperature: 0.7,
                responseMimeType: "application/json"
            }
        });

        const jsonStr = response.text.trim();
        let parsed;
        try {
            parsed = JSON.parse(jsonStr);
        } catch (e) {
            console.error(`❌ Failed to parse JSON for ${filename}:`, jsonStr);
            return null;
        }

        console.log(`✅ תוצאה ל-"${parsed.title}" [נושא: ${parsed.topic || '?'}]`);

        return { 
            title: parsed.title, 
            explanation: parsed.explanation, 
            topic: parsed.topic || '', 
            isAIGenerated: true,
            isApproved: false 
        };

    } catch (error) {
        if (retries > 0 && (error.message.includes('429') || error.message.includes('Quota'))) {
            console.log(`⚠️ חריגה ממכסת API. ממתין 15 שניות ומנסה שוב... (נשארו ${retries} נסיונות)`);
            await new Promise(r => setTimeout(r, 15000));
            return analyzeImage(filename, retries - 1);
        }
        console.error(`❌ נכשל עבור ${filename}:`, error.message);
        return null;
    }
}

async function main() {
    const allFiles = fs.readdirSync(IMAGES_DIR)
        .filter(f => /\.(png|jpe?g)$/i.test(f));

    // Find images that have the EXACT default explanation or haven't been tagged properly.
    const imagesToProcess = allFiles.filter(filename => {
        const item = data[filename];
        // Only process items that have the default stub explanation generated by auto-tag.js
        if (!item || !item.explanation) return false;
        const expl = String(item.explanation).trim();
        return expl.startsWith('משחק מילים על "') && expl.endsWith('התמונה ממחישה את הכפל המשמעות הטמון בביטוי.');
    });

    if (imagesToProcess.length === 0) {
        console.log('✅ אין תמונות שממתינות לניתוח AI.');
        return;
    }

    console.log(`🔍 נמצאו ${imagesToProcess.length} תמונות שצריכות ניתוח AI. מריץ נגלה של 100 תמונות.`);

    const limitArg = parseInt(process.argv[2], 10);
    const LIMIT = isNaN(limitArg) ? 100 : limitArg;

    const toProcess = imagesToProcess.slice(0, LIMIT);
    console.log(`Found ${imagesToProcess.length} images needing AI tags. Processing next ${toProcess.length}...`);

    let successCount = 0;

    for (const filename of toProcess) {
        // Add artificial delay to respect rate limits (15 RPM for free tier usually)
        if (successCount > 0) {
            console.log('...ממתין 6 שניות לפני הבא...');
            await new Promise(r => setTimeout(r, 6000));
        }

        const result = await analyzeImage(filename);

        if (result) {
            data[filename] = result;
            successCount++;

            // Save after every success so we don't lose data on crash
            fs.writeFileSync(DATA_FILE, JSON.stringify(data, null, 2), 'utf-8');

            // Also update the public-data.json right away using our script
            try {
                execSync('node update-public-data.mjs', { cwd: __dirname });
            } catch (e) { }
        }
    }

    console.log(`\n🎉 סיום! תויגו בהצלחה ${successCount} מתוך 10 תמונות.`);
    console.log('כדי לנתח עוד תמונות, פשוט הרץ שוב את הסקריפט.');
}

import { execSync } from 'child_process';
main();
