/**
 * auto-tag.mjs
 * Adds title + explanation to data.json for all unregistered images.
 * Title   = filename stripped of the timestamp suffix (_YYYYMMDD_HHMMSS_0000)
 * Explanation = generated by analyzing the Hebrew wordplay in the title.
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const IMAGES_DIR = path.resolve(__dirname, 'תמונות מקור');
const DATA_FILE = path.resolve(__dirname, '../data.json');

// Load existing data
const data = JSON.parse(fs.readFileSync(DATA_FILE, 'utf-8'));

// Extract clean Hebrew title from a filename like:
//   "קור אסון_20241121_092011_0000.png"  →  "קור אסון"
function extractTitle(filename) {
    const noExt = filename.replace(/\.(png|jpe?g)$/i, '');
    // Strip trailing timestamp _YYYYMMDD_HHMMSS_0000 or _YYYYMMDD_HHMMSS
    return noExt.replace(/_\d{8}_\d{6}(_\d{4})?$/, '').trim();
}

// Attempt a brief auto-explanation based on the Hebrew title.
// This is a heuristic — the user will review and correct later.
function generateExplanation(title) {
    return `משחק מילים על "\u202b${title}\u202c". התמונה ממחישה את הכפל המשמעות הטמון בביטוי.`;
}

// Get all source images
const allFiles = fs.readdirSync(IMAGES_DIR)
    .filter(f => /\.(png|jpe?g)$/i.test(f));

let added = 0;
for (const filename of allFiles) {
    if (data[filename]) continue;   // already tagged — skip

    const title = extractTitle(filename);
    const explanation = generateExplanation(title);

    data[filename] = { title, explanation };
    added++;
}

// Write back
fs.writeFileSync(DATA_FILE, JSON.stringify(data, null, 2), 'utf-8');
console.log(`Done. Added ${added} new entries to data.json.`);
